openapi: 3.0.1
info:
  title: RTD Payment Instrument Manager API
  description: ''
  version: '1.0'
servers:
  - url: http://api.cstar.pagopa.it/rtd/payment-instrument-manager
  - url: https://api.cstar.pagopa.it/rtd/payment-instrument-manager
paths:
  /salt:
    get:
      summary: Get Hash Salt
      description: Get Hash Salt
      operationId: get-hash-salt
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Salt'
              example: SALT123
  /hashed-pans:
    get:
      summary: Get Hashed PANs
      description: Get Hashed PANs
      operationId: get-hashed-pans
      responses:
        '200':
          description: 'null'
components:
  schemas:
    Salt:
      type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]