openapi: 3.0.1
info:
  title: FA IO Payment Instrument API
  description: ''
  version: '1.0'
servers:
  - url: https://api.dev.cstar.pagopa.it/fa/io/payment-instruments
paths:
  '/{id}':
    get:
      summary: find
      description: find
      operationId: findUsingGET
      parameters:
        - name: id
          in: path
          description: 'id dello strumento di pagamento, che corrisponde all''hash del PAN (Primary Account Number) del metodo di pagamento'
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Bearer Auth Token
          required: true
          schema:
            type: string
        - name: x-request-id
          in: header
          description: UUID for request identification
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentInstrumentResource'
              example:
                Status: ACTIVE
                activationDate: string
                deactivationDate: string
                fiscalCode: string
                hpan: string
        '401':
          description: ''
        '403':
          description: ''
        '500':
          description: ''
    delete:
      summary: delete
      description: delete
      operationId: deleteUsingDELETE
      parameters:
        - name: id
          in: path
          description: 'id dello strumento di pagamento, che corrisponde all''hash del PAN (Primary Account Number) del metodo di pagamento'
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Bearer Auth Token
          required: true
          schema:
            type: string
        - name: x-request-id
          in: header
          description: UUID for request identification
          schema:
            type: string
      responses:
        '204':
          description: ''
        '400':
          description: ''
        '401':
          description: ''
        '500':
          description: ''
    put:
      summary: enrollmentPaymentInstrumentIO
      description: enrollmentPaymentInstrumentIO
      operationId: enrollmentPaymentInstrumentIOUsingPUT
      parameters:
        - name: id
          in: path
          description: 'id dello strumento di pagamento, che corrisponde all’hash del PAN (Primary Account Number) del metodo di pagamento'
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Bearer Auth Token
          required: true
          schema:
            type: string
        - name: x-request-id
          in: header
          description: UUID for request identification
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollPaymentInstrumentResource'
              example:
                activationDate: string
        '401':
          description: ''
        '403':
          description: ''
        '500':
          description: ''
components:
  schemas:
    PaymentInstrumentResource:
      title: PaymentInstrumentResource
      required:
        - Status
        - activationDate
        - deactivationDate
        - fiscalCode
        - hpan
      type: object
      properties:
        Status:
          enum:
            - ACTIVE
            - INACTIVE
          type: string
          description: 'stato dello strumento di pagamento. Può assumere i seguenti valori:ACTIVE,INACTIVE'
        activationDate:
          type: string
          description: timestamp dell'attivazione dello strumento di pagamento. FORMATO  ISO8601 yyyy-MM-ddTHH:mm:ss.SSSXXXXX
          format: date-time
        deactivationDate:
          type: string
          description: timestamp della disattivazione dello strumento di pagamento. FORMATO  ISO8601 yyyy-MM-ddTHH:mm:ss.SSSXXXXX
          format: date-time
        fiscalCode:
          type: string
          description: 'id dell''utente, che corrisponde al codice fiscale'
        hpan:
          type: string
          description: 'id dello strumento di pagamento, che corrisponde all''hash del PAN (Primary Account Number) del metodo di pagamento'
    EnrollPaymentInstrumentResource:
      title: EnrollmentPaymentInstrumentResource
      type: object
      properties:
        activationDate:
          type: string
          description: Timestamp dell’attivazione dello strumento di pagamento. FORMATO  ISO8601 yyyy-MM-ddTHH:mm:ss.SSSXXXXX
          format: date-time
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]